DROP TABLE IF EXISTS security_daily_marketdata_shares;
CREATE TABLE security_daily_marketdata_shares
  (
    tech$load_id                     INTEGER NOT NULL,
    tech$effective_dt                TEXT    NOT NULL,
    tech$expiration_dt               TEXT    NOT NULL,
    tech$last_seen_dt                TEXT    NOT NULL,
    tech$hash_value                  TEXT    NOT NULL,
    security_id                      TEXT    NOT NULL,
    board_id                         TEXT    NOT NULL,
    bid                              REAL,
    bid_depth                        TEXT    NOT NULL,
    offer                            REAL,
    offer_depth                      TEXT    NOT NULL,
    spread                           REAL    NOT NULL,
    bid_deptht                       INTEGER NOT NULL,
    offer_deptht                     INTEGER NOT NULL,
    open                             REAL,
    low                              REAL,
    high                             REAL,
    last                             REAL,
    last_change                      REAL    NOT NULL,
    last_change_prcnt                REAL    NOT NULL,
    qty                              INTEGER NOT NULL,
    value                            REAL    NOT NULL,
    value_usd                        REAL    NOT NULL,
    wa_price                         REAL,
    last_cng_to_last_wa_price_prcnt  REAL    NOT NULL,
    wap_to_prev_wa_price_prcnt       REAL    NOT NULL,
    wap_to_prev_wa_price             REAL    NOT NULL,
    close_price                      REAL,
    market_price_to_day              REAL,
    market_price                     REAL,
    last_to_prev_price               REAL    NOT NULL,
    num_trades                       INTEGER NOT NULL,
    vol_to_day                       INTEGER NOT NULL,
    val_to_day                       INTEGER NOT NULL,
    val_to_day_usd                   INTEGER NOT NULL,
    etf_settle_price                 REAL,
    trading_status                   TEXT    NOT NULL,
    update_time                      TEXT    NOT NULL,
    admitted_quote                   REAL,
    last_bid                         TEXT    NOT NULL,
    last_offer                       TEXT    NOT NULL,
    l_close_price                    REAL,
    l_current_price                  REAL,
    market_price_2                   REAL,
    num_bids                         TEXT    NOT NULL,
    num_offers                       TEXT    NOT NULL,
    chage                            REAL,
    time                             TEXT    NOT NULL,
    high_bid                         TEXT    NOT NULL,
    low_offer                        TEXT    NOT NULL,
    price_minus_prev_wa_price        REAL,
    open_period_price                REAL,
    seq_num                          INTEGER NOT NULL,
    sys_time                         TEXT    NOT NULL,
    closing_auction_price            REAL,
    closing_auction_volume           REAL,
    issue_capitalization             REAL,
    issue_capitalization_update_time TEXT    NOT NULL,
    etf_settle_currency              TEXT    NOT NULL,
    val_to_day_rur                   INTEGER NOT NULL,
    trading_session                  TEXT    NOT NULL,
    PRIMARY KEY(security_id, board_id, tech$effective_dt)
  )
WITHOUT ROWID;
