INSERT
  INTO security_markets
  (
    tech$load_id,
    tech$load_dttm,
    id,
    trade_engine_id,
    trade_engine_name,
    trade_engine_title,
    market_name,
    market_title,
    market_id,
    market_place
  )
VALUES
  (
    :tech$load_id,
    :tech$load_dttm,
    :id,
    :trade_engine_id,
    :trade_engine_name,
    :trade_engine_title,
    :market_name,
    :market_title,
    :market_id,
    :market_place
  )
