INSERT
  INTO security_board_groups
  (
    tech$load_id,
    tech$load_dttm,
    id,
    trade_engine_id,
    trade_engine_name,
    trade_engine_title,
    market_id,
    market_name,
    name,
    title,
    is_default,
    board_group_id,
    is_traded
  )
VALUES
  (
    :tech$load_id,
    :tech$load_dttm,
    :id,
    :trade_engine_id,
    :trade_engine_name,
    :trade_engine_title,
    :market_id,
    :market_name,
    :name,
    :title,
    :is_default,
    :board_group_id,
    :is_traded
  )
