INSERT
  INTO security_daily_marketdata_bonds
  (
    tech$load_id,
    tech$effective_dt,
    tech$expiration_dt,
    tech$last_seen_dt,
    tech$hash_value,
    security_id,
    bid,
    bid_depth,
    offer,
    offer_depth,
    spread,
    bid_deptht,
    offer_deptht,
    open,
    low,
    high,
    last,
    last_change,
    last_change_prcnt,
    qty,
    value,
    yield,
    value_usd,
    wa_price,
    last_cng_to_last_wa_price_prcnt,
    wap_to_prev_wa_price_prcnt,
    wap_to_prev_wa_price,
    yield_at_wa_price,
    yield_to_prev_yield,
    close_yield,
    close_price,
    market_price_to_day,
    market_price,
    last_to_prev_price,
    num_trades,
    vol_to_day,
    val_to_day,
    val_to_day_usd,
    board_id,
    trading_status,
    update_time,
    duration,
    num_bids,
    num_offers,
    change,
    time,
    high_bid,
    low_offer,
    price_minus_prev_wa_price,
    last_bid,
    last_offer,
    l_current_price,
    l_close_price,
    market_price_2,
    admitted_quote,
    open_period_price,
    seq_num,
    sys_time,
    val_to_day_rur,
    iri_cpi_close,
    bei_close,
    cbr_close,
    yield_to_offer,
    yield_last_coupon,
    trading_session
  )
SELECT
       :tech$load_id       AS tech$load_id,
       tech$effective_dt,
       tech$expiration_dt,
       tech$last_seen_dt,
       tech$hash_value,
       security_id,
       bid,
       bid_depth,
       offer,
       offer_depth,
       spread,
       bid_deptht,
       offer_deptht,
       open,
       low,
       high,
       last,
       last_change,
       last_change_prcnt,
       qty,
       value,
       yield,
       value_usd,
       wa_price,
       last_cng_to_last_wa_price_prcnt,
       wap_to_prev_wa_price_prcnt,
       wap_to_prev_wa_price,
       yield_at_wa_price,
       yield_to_prev_yield,
       close_yield,
       close_price,
       market_price_to_day,
       market_price,
       last_to_prev_price,
       num_trades,
       vol_to_day,
       val_to_day,
       val_to_day_usd,
       board_id,
       trading_status,
       update_time,
       duration,
       num_bids,
       num_offers,
       change,
       time,
       high_bid,
       low_offer,
       price_minus_prev_wa_price,
       last_bid,
       last_offer,
       l_current_price,
       l_close_price,
       market_price_2,
       admitted_quote,
       open_period_price,
       seq_num,
       sys_time,
       val_to_day_rur,
       iri_cpi_close,
       bei_close,
       cbr_close,
       yield_to_offer,
       yield_last_coupon,
       trading_session
  FROM (SELECT
               tech$effective_dt,
               tech$expiration_dt,
               tech$last_seen_dt,
               tech$hash_value,
               security_id,
               bid,
               bid_depth,
               offer,
               offer_depth,
               spread,
               bid_deptht,
               offer_deptht,
               open,
               low,
               high,
               last,
               last_change,
               last_change_prcnt,
               qty,
               value,
               yield,
               value_usd,
               wa_price,
               last_cng_to_last_wa_price_prcnt,
               wap_to_prev_wa_price_prcnt,
               wap_to_prev_wa_price,
               yield_at_wa_price,
               yield_to_prev_yield,
               close_yield,
               close_price,
               market_price_to_day,
               market_price,
               last_to_prev_price,
               num_trades,
               vol_to_day,
               val_to_day,
               val_to_day_usd,
               board_id,
               trading_status,
               update_time,
               duration,
               num_bids,
               num_offers,
               change,
               time,
               high_bid,
               low_offer,
               price_minus_prev_wa_price,
               last_bid,
               last_offer,
               l_current_price,
               l_close_price,
               market_price_2,
               admitted_quote,
               open_period_price,
               seq_num,
               sys_time,
               val_to_day_rur,
               iri_cpi_close,
               bei_close,
               cbr_close,
               yield_to_offer,
               yield_last_coupon,
               trading_session
          FROM tech$security_daily_marketdata_bonds src
         WHERE NOT EXISTS(SELECT
                                 NULL
                            FROM security_daily_marketdata_bonds sat
                           WHERE
                                 sat.security_id = src.security_id
                             AND sat.board_id = src.board_id
                             AND sat.tech$expiration_dt = '2999-12-31')
         UNION ALL
        SELECT
               CASE mrg.flg
                    WHEN 'INSERT' THEN
                        tech$effective_dt
                    WHEN 'UPDATE' THEN
                        tech$sat$effective_dt
               END AS tech$effective_dt,
               CASE mrg.flg
                    WHEN 'INSERT' THEN
                        tech$expiration_dt
                    WHEN 'UPDATE' THEN
                        CASE upsert_flg
                             WHEN 'UPSERT' THEN
                                 tech$sat$expiration_dt
                             ELSE
                                 tech$expiration_dt
                        END
               END AS tech$expiration_dt,
               tech$last_seen_dt,
               tech$hash_value,
               security_id,
               bid,
               bid_depth,
               offer,
               offer_depth,
               spread,
               bid_deptht,
               offer_deptht,
               open,
               low,
               high,
               last,
               last_change,
               last_change_prcnt,
               qty,
               value,
               yield,
               value_usd,
               wa_price,
               last_cng_to_last_wa_price_prcnt,
               wap_to_prev_wa_price_prcnt,
               wap_to_prev_wa_price,
               yield_at_wa_price,
               yield_to_prev_yield,
               close_yield,
               close_price,
               market_price_to_day,
               market_price,
               last_to_prev_price,
               num_trades,
               vol_to_day,
               val_to_day,
               val_to_day_usd,
               board_id,
               trading_status,
               update_time,
               duration,
               num_bids,
               num_offers,
               change,
               time,
               high_bid,
               low_offer,
               price_minus_prev_wa_price,
               last_bid,
               last_offer,
               l_current_price,
               l_close_price,
               market_price_2,
               admitted_quote,
               open_period_price,
               seq_num,
               sys_time,
               val_to_day_rur,
               iri_cpi_close,
               bei_close,
               cbr_close,
               yield_to_offer,
               yield_last_coupon,
               trading_session
          FROM (SELECT
                       tech$effective_dt,
                       tech$expiration_dt,
                       tech$last_seen_dt,
                       tech$sat$effective_dt,
                       tech$sat$expiration_dt,
                       tech$hash_value,
                       security_id,
                       bid,
                       bid_depth,
                       offer,
                       offer_depth,
                       spread,
                       bid_deptht,
                       offer_deptht,
                       open,
                       low,
                       high,
                       last,
                       last_change,
                       last_change_prcnt,
                       qty,
                       value,
                       yield,
                       value_usd,
                       wa_price,
                       last_cng_to_last_wa_price_prcnt,
                       wap_to_prev_wa_price_prcnt,
                       wap_to_prev_wa_price,
                       yield_at_wa_price,
                       yield_to_prev_yield,
                       close_yield,
                       close_price,
                       market_price_to_day,
                       market_price,
                       last_to_prev_price,
                       num_trades,
                       vol_to_day,
                       val_to_day,
                       val_to_day_usd,
                       board_id,
                       trading_status,
                       update_time,
                       duration,
                       num_bids,
                       num_offers,
                       change,
                       time,
                       high_bid,
                       low_offer,
                       price_minus_prev_wa_price,
                       last_bid,
                       last_offer,
                       l_current_price,
                       l_close_price,
                       market_price_2,
                       admitted_quote,
                       open_period_price,
                       seq_num,
                       sys_time,
                       val_to_day_rur,
                       iri_cpi_close,
                       bei_close,
                       cbr_close,
                       yield_to_offer,
                       yield_last_coupon,
                       trading_session,
                       CASE
                            WHEN rn = 1
                             AND fv_equal_flag = 'NON_EQUAL'
                             AND tech$effective_dt = tech$sat$effective_dt THEN
                                'UPDATE'
                            WHEN rn = 1
                              OR rn = 2 AND fv_equal_flag = 'EQUAL' THEN
                                'UPSERT'
                            ELSE
                                'INSERT'
                       END AS upsert_flg
                  FROM (SELECT
                               src.tech$effective_dt,
                               src.tech$expiration_dt,
                               src.tech$last_seen_dt,
                               sat.tech$effective_dt                 AS tech$sat$effective_dt,
                               DATE(src.tech$effective_dt, '-1 DAY') AS tech$sat$expiration_dt,
                               src.tech$hash_value,
                               src.security_id,
                               src.bid,
                               src.bid_depth,
                               src.offer,
                               src.offer_depth,
                               src.spread,
                               src.bid_deptht,
                               src.offer_deptht,
                               src.open,
                               src.low,
                               src.high,
                               src.last,
                               src.last_change,
                               src.last_change_prcnt,
                               src.qty,
                               src.value,
                               src.yield,
                               src.value_usd,
                               src.wa_price,
                               src.last_cng_to_last_wa_price_prcnt,
                               src.wap_to_prev_wa_price_prcnt,
                               src.wap_to_prev_wa_price,
                               src.yield_at_wa_price,
                               src.yield_to_prev_yield,
                               src.close_yield,
                               src.close_price,
                               src.market_price_to_day,
                               src.market_price,
                               src.last_to_prev_price,
                               src.num_trades,
                               src.vol_to_day,
                               src.val_to_day,
                               src.val_to_day_usd,
                               src.board_id,
                               src.trading_status,
                               src.update_time,
                               src.duration,
                               src.num_bids,
                               src.num_offers,
                               src.change,
                               src.time,
                               src.high_bid,
                               src.low_offer,
                               src.price_minus_prev_wa_price,
                               src.last_bid,
                               src.last_offer,
                               src.l_current_price,
                               src.l_close_price,
                               src.market_price_2,
                               src.admitted_quote,
                               src.open_period_price,
                               src.seq_num,
                               src.sys_time,
                               src.val_to_day_rur,
                               src.iri_cpi_close,
                               src.bei_close,
                               src.cbr_close,
                               src.yield_to_offer,
                               src.yield_last_coupon,
                               src.trading_session,
                               FIRST_VALUE(CASE
                                                WHEN src.tech$hash_value != sat.tech$hash_value THEN
                                                    'NON_EQUAL'
                                                ELSE
                                                    'EQUAL'
                                           END) OVER (wnd) AS fv_equal_flag,
                               ROW_NUMBER() OVER (wnd)     AS rn
                          FROM tech$security_daily_marketdata_bonds src
                               JOIN
                               security_daily_marketdata_bonds sat
                                   ON
                                      sat.security_id = src.security_id
                                  AND sat.board_id = src.board_id
                                  AND sat.tech$effective_dt <= src.tech$effective_dt
                                  AND sat.tech$expiration_dt = '2999-12-31'
                        WINDOW wnd AS (PARTITION BY src.security_id,
                                                    src.board_id
                                           ORDER BY src.tech$effective_dt))
                 WHERE rn = 1 AND fv_equal_flag = 'NON_EQUAL'
                    OR rn > 1) src
               CROSS JOIN
               (SELECT 'INSERT' AS flg
                 UNION ALL
                SELECT 'UPDATE' AS flg) mrg
    WHERE src.upsert_flg = 'UPSERT'
       OR src.upsert_flg = mrg.flg)
 WHERE 1 = 1
 ON CONFLICT(security_id, board_id, tech$effective_dt)
 DO UPDATE
       SET tech$expiration_dt = excluded.tech$expiration_dt,
           tech$last_seen_dt = excluded.tech$last_seen_dt,
           tech$load_id = excluded.tech$load_id,
           tech$hash_value = CASE
                                  WHEN tech$expiration_dt = '2999-12-31'
                                   AND excluded.tech$expiration_dt = '2999-12-31' THEN
                                      excluded.tech$hash_value
                                  ELSE
                                      tech$hash_value
                             END,
           bid = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.bid ELSE bid END,
           bid_depth = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.bid_depth ELSE bid_depth END,
           offer = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.offer ELSE offer END,
           offer_depth = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.offer_depth ELSE offer_depth END,
           spread = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.spread ELSE spread END,
           bid_deptht = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.bid_deptht ELSE bid_deptht END,
           offer_deptht = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.offer_deptht ELSE offer_deptht END,
           open = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.open ELSE open END,
           low = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.low ELSE low END,
           high = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.high ELSE high END,
           last = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last ELSE last END,
           last_change = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last_change ELSE last_change END,
           last_change_prcnt = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last_change_prcnt ELSE last_change_prcnt END,
           qty = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.qty ELSE qty END,
           value = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.value ELSE value END,
           yield = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.yield ELSE yield END,
           value_usd = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.value_usd ELSE value_usd END,
           wa_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.wa_price ELSE wa_price END,
           last_cng_to_last_wa_price_prcnt = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last_cng_to_last_wa_price_prcnt ELSE last_cng_to_last_wa_price_prcnt END,
           wap_to_prev_wa_price_prcnt = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.wap_to_prev_wa_price_prcnt ELSE wap_to_prev_wa_price_prcnt END,
           wap_to_prev_wa_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.wap_to_prev_wa_price ELSE wap_to_prev_wa_price END,
           yield_at_wa_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.yield_at_wa_price ELSE yield_at_wa_price END,
           yield_to_prev_yield = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.yield_to_prev_yield ELSE yield_to_prev_yield END,
           close_yield = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.close_yield ELSE close_yield END,
           close_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.close_price ELSE close_price END,
           market_price_to_day = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.market_price_to_day ELSE market_price_to_day END,
           market_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.market_price ELSE market_price END,
           last_to_prev_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last_to_prev_price ELSE last_to_prev_price END,
           num_trades = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.num_trades ELSE num_trades END,
           vol_to_day = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.vol_to_day ELSE vol_to_day END,
           val_to_day = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.val_to_day ELSE val_to_day END,
           val_to_day_usd = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.val_to_day_usd ELSE val_to_day_usd END,
           trading_status = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.trading_status ELSE trading_status END,
           update_time = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.update_time ELSE update_time END,
           duration = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.duration ELSE duration END,
           num_bids = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.num_bids ELSE num_bids END,
           num_offers = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.num_offers ELSE num_offers END,
           change = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.change ELSE change END,
           time = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.time ELSE time END,
           high_bid = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.high_bid ELSE high_bid END,
           low_offer = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.low_offer ELSE low_offer END,
           price_minus_prev_wa_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.price_minus_prev_wa_price ELSE price_minus_prev_wa_price END,
           last_bid = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last_bid ELSE last_bid END,
           last_offer = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.last_offer ELSE last_offer END,
           l_current_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.l_current_price ELSE l_current_price END,
           l_close_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.l_close_price ELSE l_close_price END,
           market_price_2 = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.market_price_2 ELSE market_price_2 END,
           admitted_quote = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.admitted_quote ELSE admitted_quote END,
           open_period_price = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.open_period_price ELSE open_period_price END,
           seq_num = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.seq_num ELSE seq_num END,
           sys_time = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.sys_time ELSE sys_time END,
           val_to_day_rur = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.val_to_day_rur ELSE val_to_day_rur END,
           iri_cpi_close = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.iri_cpi_close ELSE iri_cpi_close END,
           bei_close = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.bei_close ELSE bei_close END,
           cbr_close = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.cbr_close ELSE cbr_close END,
           yield_to_offer = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.yield_to_offer ELSE yield_to_offer END,
           yield_last_coupon = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.yield_last_coupon ELSE yield_last_coupon END,
           trading_session = CASE WHEN tech$expiration_dt = '2999-12-31' AND excluded.tech$expiration_dt = '2999-12-31' THEN excluded.trading_session ELSE trading_session END
