DROP TABLE IF EXISTS security_rate_bonds;
CREATE TABLE security_rate_bonds
  (
    tech$load_id                INTEGER NOT NULL,
    tech$load_dttm              TEXT    NOT NULL,
    board_id                    TEXT,
    trade_date                  TEXT,
    short_name                  TEXT,
    security_id                 TEXT,
    num_trades                  REAL,
    value                       REAL,
    low                         REAL,
    high                        REAL,
    close                       REAL,
    legal_close_price           REAL,
    acc_int                     REAL,
    wa_price                    REAL,
    yield_close                 REAL,
    open                        REAL,
    volume                      REAL,
    market_price_2              REAL,
    market_price_3              REAL,
    admitted_quote              REAL,
    mp2_val_trd                 REAL,
    market_price_3_trades_value REAL,
    admitted_value              REAL,
    mat_date                    TEXT,
    duration                    REAL,
    yield_at_map                REAL,
    iri_cpi_close               REAL,
    bei_close                   REAL,
    coupon_percent              REAL,
    coupon_value                REAL,
    buy_back_date               TEXT,
    last_trade_date             TEXT,
    face_value                  REAL,
    currency_id                 TEXT,
    cbr_close                   REAL,
    yield_to_offer              REAL,
    yield_last_coupon           REAL,
    offer_date                  TEXT,
    face_unit                   TEXT,
    trading_session             INTEGER
  );
